[package]
name = "meyda"
version = "0.1.0"
authors = ["jakubfiala <mu201jf@gold.ac.uk>"]
edition = "2021"

[dependencies]
rustfft = "6.0.1"

[dev-dependencies]
approx = "0.5.1"
serde = "1.0.7"
serde_derive = "1.0.7"
serde_json = "1.0"
